language: python
sudo: required

cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

matrix:
  include:
    - os: linux
      services: docker
      python: 3.5
      env:
        - RUN="docker run --rm -e PYTHON_VERSION=cp35-cp35m -v $(pwd):/host -w /host henriquegemignani/docker-nod-ci"

    - os: linux
      services: docker
      python: 3.6
      env:
        - INCLUDE_SDIST=true
        - RUN="docker run --rm -e PYTHON_VERSION=cp36-cp36m -v $(pwd):/host -w /host henriquegemignani/docker-nod-ci"

    # - os: osx
    #   osx_image: xcode9.4
    #   language: generic
    #   env:
    #     - PYENV_VERSION=3.6.5
    #     - RUN=bash

    # - os: osx
    #   osx_image: xcode9.4
    #   language: generic
    #   env:
    #     - PYENV_VERSION=3.7.0
    #     - RUN=bash

deploy:
  provider: script
  script: python -m twine upload dist/*.whl
  skip_cleanup: true
  on:
    tags: true

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull henriquegemignani/docker-nod-ci; fi
- |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
- python --version

install:
- python -m pip install --upgrade setuptools>=38.6.0 twine>=1.11.0 wheel>=0.31.0 pytest Cython

script:
- $RUN ./travis-scripts/build.sh
- sudo chown -R $(whoami) .
- python -m pip install --upgrade dist/*
- python -m pytest
- if [[ "$INCLUDE_SDIST" == "true" ]]; then python setup.py sdist; fi
